# Generated by Django 5.1.6 on 2025-02-27 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('naics', models.IntegerField()),
                ('new_exist', models.IntegerField()),
                ('retained_job', models.IntegerField()),
                ('franchise_code', models.IntegerField()),
                ('urban_rural', models.IntegerField()),
                ('gr_appv', models.FloatField()),
                ('bank', models.CharField(max_length=255)),
                ('term', models.IntegerField()),
                ('prediction', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('ai_approved', 'Approuvé par IA'), ('ai_rejected', 'Rejeté par IA'), ('advisor_approved', 'Approuvé par conseiller'), ('advisor_rejected', 'Rejeté par conseiller')], default='pending', max_length=20)),
                ('advisor_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
