services:
  django:
    build:
      context: .
      dockerfile: Dockerfile  
    container_name: django
    env_file: .env
    networks:
      - Bamk_network
    volumes:
      - .:/app
      - media_volume:/app/media
    expose:
      - "8080"
    command: daphne -b 0.0.0.0 -p 8080 Bamk.asgi:application

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    networks:
      - Bamk_network
    ports:
      - "80:80"
    volumes:
      - media_volume:/app/media
    depends_on:
      - django

volumes:
  media_volume:

networks:
  Bamk_network:
    external: true
